/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Build version + commit SHA + build date. */
        get: operations["getVersion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/whoami": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Identity yafu inferred for the request. */
        get: operations["getWhoami"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/clusters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List registered clusters with probe status. */
        get: operations["listClusters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listApplications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listSources"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAlerts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/image-updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listImageUpdates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description One per-cluster failure during a fan-out list. */
        ClusterError: {
            cluster: string;
            error: string;
        };
        /** @description Registered cluster summary used by the Fleet view. */
        Cluster: {
            id: string;
            name: string;
            region?: string;
            env?: string;
            /** @enum {string} */
            status: "healthy" | "degraded" | "failing" | "unreachable";
            apps: number;
            ready: number;
            failing: number;
            suspended: number;
            sources: number;
            version?: string;
            reachable: boolean;
            fluxInstalled: boolean;
            lastError?: string;
            spark?: number[];
        };
        ClustersResponse: {
            clusters: components["schemas"]["Cluster"][];
        };
        /** @description Unified row for a Kustomization or HelmRelease. */
        Application: {
            id: string;
            name: string;
            /** @enum {string} */
            kind: "Kustomization" | "HelmRelease";
            ns: string;
            /** @description Display name. */
            cluster: string;
            /** @description Registry id, URL-safe. */
            clusterId: string;
            /** @enum {string} */
            status: "healthy" | "degraded" | "failing" | "progressing" | "paused";
            /** @enum {string} */
            sync: "Synced" | "OutOfSync" | "Progressing" | "Suspended";
            source: string;
            revision: string;
            age: string;
            message?: string;
            suspended: boolean;
            replicas?: string;
        };
        ApplicationsResponse: {
            applications: components["schemas"]["Application"][];
            errors?: components["schemas"]["ClusterError"][];
        };
        /** @description FluxCD Source resource. */
        Source: {
            id: string;
            name: string;
            /** @enum {string} */
            kind: "GitRepository" | "HelmRepository" | "OCIRepository" | "Bucket";
            ns: string;
            cluster: string;
            clusterId: string;
            url: string;
            ref?: string;
            revision?: string;
            /** @enum {string} */
            status: "healthy" | "degraded" | "failing" | "progressing" | "paused";
            interval?: string;
            age: string;
            message?: string;
            suspended: boolean;
        };
        SourcesResponse: {
            sources: components["schemas"]["Source"][];
            errors?: components["schemas"]["ClusterError"][];
        };
        Alert: {
            id: string;
            name: string;
            cluster: string;
            clusterId: string;
            ns: string;
            /** @description Resolved provider type or 'missing' when the Provider ref is broken. */
            provider: string;
            /** @enum {string} */
            severity: "info" | "error";
            target?: string;
            /** @enum {string} */
            status: "healthy" | "paused";
            suspended: boolean;
            age: string;
        };
        AlertsResponse: {
            alerts: components["schemas"]["Alert"][];
            errors?: components["schemas"]["ClusterError"][];
        };
        FluxEvent: {
            id: string;
            /** @description RFC3339 timestamp. */
            t: string;
            cluster: string;
            clusterId: string;
            ns: string;
            /** @enum {string} */
            kind: "ok" | "warn" | "err";
            /** @enum {string} */
            type: "Normal" | "Warning";
            reason: string;
            message: string;
            /** @description <Kind>/<name>. */
            object: string;
            source: string;
        };
        EventsResponse: {
            events: components["schemas"]["FluxEvent"][];
            errors?: components["schemas"]["ClusterError"][];
        };
        ImageUpdate: {
            id: string;
            name: string;
            cluster: string;
            clusterId: string;
            ns: string;
            image: string;
            latestTag?: string;
            /** @description "semver:RANGE" | "alphabetical" | "numerical" | "" when malformed. */
            policy: string;
            /** @enum {string} */
            status: "ready" | "failing" | "progressing" | "paused";
            age: string;
            message?: string;
            suspended: boolean;
        };
        ImageUpdatesResponse: {
            updates: components["schemas"]["ImageUpdate"][];
            errors?: components["schemas"]["ClusterError"][];
        };
        AppHistoryEntry: {
            revision: string;
            status?: string;
            action?: string;
            appVersion?: string;
            timestamp?: string;
            current: boolean;
        };
        AppHistoryResponse: {
            appId: string;
            entries: components["schemas"]["AppHistoryEntry"][];
            note?: string;
        };
        TreeNode: {
            group?: string;
            version?: string;
            kind: string;
            ns?: string;
            name: string;
            /** @enum {string} */
            status: "ready" | "failing" | "progressing" | "notfound" | "unknown";
            message?: string;
        };
        TreeResponse: {
            appId: string;
            nodes: components["schemas"]["TreeNode"][];
            note?: string;
        };
        ManifestResponse: {
            appId: string;
            kind: string;
            yaml: string;
        };
        ManagedField: {
            manager: string;
            /** @enum {string} */
            operation: "Apply" | "Update";
            time?: string;
            /** @description True when the manager is not a known Flux controller. */
            foreign: boolean;
        };
        DriftedResource: {
            group?: string;
            version?: string;
            kind: string;
            ns?: string;
            name: string;
            /** @enum {string} */
            status: "ready" | "drift" | "notfound" | "unknown";
            managers?: components["schemas"]["ManagedField"][];
        };
        DiffResponse: {
            appId: string;
            resources: components["schemas"]["DriftedResource"][];
            note?: string;
        };
        PodInfo: {
            ns: string;
            name: string;
            /** @enum {string} */
            phase: "Pending" | "Running" | "Succeeded" | "Failed" | "Unknown";
            containers: string[];
            restarts: number;
            age: string;
        };
        LogsResponse: {
            appId: string;
            pods: components["schemas"]["PodInfo"][];
            /** @description ns/name of the pod. */
            selected?: string;
            container?: string;
            logs?: string;
            truncated?: boolean;
            note?: string;
        };
        RenderLine: {
            /** @enum {string} */
            kind: "context" | "add" | "del" | "empty";
            desiredLn?: number;
            liveLn?: number;
            text: string;
        };
        RenderHunk: {
            label: string;
            lines: components["schemas"]["RenderLine"][];
        };
        RenderResource: {
            group?: string;
            version?: string;
            kind: string;
            ns?: string;
            name: string;
            /** @enum {string} */
            status: "in-sync" | "drifted" | "missing-on-cluster" | "extra-on-cluster" | "render-error";
            hunks?: components["schemas"]["RenderHunk"][];
            renderError?: string;
            /** @enum {string} */
            reconcileWould?: "create" | "update" | "delete";
        };
        RenderSource: {
            name: string;
            namespace: string;
            /** @enum {string} */
            kind: "GitRepository" | "HelmRepository" | "OCIRepository" | "Bucket";
            ref?: string;
            revision: string;
            /** @enum {string} */
            method: "kustomize build" | "helm template";
        };
        RenderResponse: {
            appId: string;
            source: components["schemas"]["RenderSource"];
            renderedAt: string;
            resources: components["schemas"]["RenderResource"][];
            error?: string;
        };
        WhoamiResponse: {
            subject: string;
            email?: string;
            name?: string;
            groups?: string[];
            isAnonymous: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getVersion: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    getWhoami: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WhoamiResponse"];
                };
            };
        };
    };
    listClusters: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClustersResponse"];
                };
            };
        };
    };
    listApplications: {
        parameters: {
            query?: {
                /** @description Restrict to a single cluster (registry id). */
                cluster?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationsResponse"];
                };
            };
        };
    };
    listSources: {
        parameters: {
            query?: {
                cluster?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourcesResponse"];
                };
            };
        };
    };
    listAlerts: {
        parameters: {
            query?: {
                cluster?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertsResponse"];
                };
            };
        };
    };
    listEvents: {
        parameters: {
            query?: {
                cluster?: string;
                ns?: string;
                kind?: string;
                name?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
        };
    };
    listImageUpdates: {
        parameters: {
            query?: {
                cluster?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description ok */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageUpdatesResponse"];
                };
            };
        };
    };
}
